<a href="https://colab.research.google.com/github/purushottamk3112/Learn_numpy/blob/main/Learn_Numpy_withEase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***We are earning Numpy from scratch
Prequistes:- Python foundation,matrices{finding compliments,multiplication}
***

In [ ]:
# we will import numpy in python using
import numpy as np #you can use any naming convention instead of np


In [ ]:
#simple way to define numpy array
nump_1d=np.array([1,2,3,4,5])
print(nump_1d)

#way to print 2-d array,we can do similar for n-d arrays
nump_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(nump_2d)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


***Multiplicaton on list and numpy arrays***

In [ ]:
lis_1d=[1,2,3]
print(lis_1d*3)

#multiplication on numpy array
nump_1d=np.array([[1,2,3],[4,5,6]])
print(nump_1d*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[[ 3  6  9]
 [12 15 18]]


***Ways to declare numpy Arrays***

******

In [10]:
zeros = np.zeros((3,3))
print("zeros in array",zeros)

ones=np.ones((4,3))
print("ones in array",ones)

full=np.full((3,4),7)
print("full in array",full)

random=np.random.random((4,3))
print("random in array",random)

#we also have method called 'arrange' where ((start,stop),**)


zeros in array [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones in array [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full in array [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random in array [[0.1530802  0.18254074 0.98613447]
 [0.71462645 0.30787232 0.54823799]
 [0.74281943 0.26643968 0.23077242]
 [0.48911975 0.28876589 0.54950158]]


***Vectors,scaler and Tensors***