<a href="https://colab.research.google.com/github/purushottamk3112/Learn_numpy/blob/main/Learn_Numpy_withEase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# We are earning Numpy from scratch
#Prequistes:- Python foundation,matrices{finding compliments,multiplication}


In [ ]:
# we will import numpy in python using
import numpy as np #you can use any naming convention instead of np


In [ ]:
#simple way to define numpy array
nump_1d=np.array([1,2,3,4,5])
print(nump_1d)

#way to print 2-d array,we can do similar for n-d arrays
nump_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(nump_2d)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#Multiplicaton on list and numpy arrays

lis_1d=[1,2,3]
print(lis_1d*3)

#multiplication on numpy array
nump_1d=np.array([1,2,3])
print(nump_1d*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]
